### ISSUE TITLE
[Question] Is DataGrid in process?

### ISSUE THREAD

**Issue by jzlhll** [modern-forms/Modern.Forms#12]
Hello, just see this sample controls. 
It is pretty good for me (Winforms developer).
If the DataGrid control is on the way, I can port my winform app to osx.

**Comment by jpobst** [comment]
There is not currently a DataGrid control.  We will definitely need one, but it is a very complex control to make.

Out of curiosity, do you just need to display data in a data grid? Or do you need the ability for users to edit that data as well?

**Comment by jzlhll** [comment]
> There is not currently a DataGrid control. We will definitely need one, but it is a very complex control to make.
> 
> Out of curiosity, do you just need to display data in a data grid? Or do you need the ability for users to edit that data as well?

The current，I'm seeking for show data one line by one line with many columns. Do not need edit yet. Maybe it can be shown by listview with complex item design.

**Comment by jzlhll** [comment]
Close it, wait for author's next job.
