### ISSUE TITLE
Good job

### ISSUE THREAD

**Issue by JamRemco** [modern-forms/Modern.Forms#13]
Hello world!,

Nice, but still a lot work to do.

You probevly know but on listlike controls such as listbox, combo, treeview etc. there is no hoverOver indicator wich is a bit anoying.
Also there is no keyvoard Suport om such controls. which is IMO essencial.
Selction on textbox is broken or incomplete.

That having said, still promising
If i can help in any way let me know.

Regards,

Remco

**Comment by jpobst** [comment]
Thanks!

Indeed there is still a lot of work to be done to be a fully fledged toolkit.

Hover support was added to ListBox last week: https://github.com/modern-forms/Modern.Forms/commit/22f7092bed3a450fd524e5493e939747b2c5cb87#diff-4c7778f45d22188b5860b38bb3bc7892R302.  ComboBox uses the ListBox for its drop-down, so it supports hover now as well.

There is currently no keyboard navigation support (other than tabbing between controls), I would suspect that to be in 0.3 - 0.4 timeframe.
