### ISSUE TITLE
3 issues and suggest about TextBox

### ISSUE THREAD

**Issue by jzlhll** [modern-forms/Modern.Forms#16]
Hello, I'm very interested in this proj.
Below is some bugs or suggest for TextBox.
Please check it and merge.

**Next time I will try to use pullRequest.** 

1. TextBox do not support Multi-Chars input. This patch can support it.

> diff --git a/src/Modern.Forms/KeyPressEventArgs.cs b/src/Modern.Forms/KeyPressEventArgs.cs
index 5afe50d..56b88f6 100644
--- a/src/Modern.Forms/KeyPressEventArgs.cs
+++ b/src/Modern.Forms/KeyPressEventArgs.cs
@@ -32,17 +32,20 @@ namespace Modern.Forms
     {
         private readonly Keys key_data;
\-        public KeyPressEventArgs (char keyChar, Keys keyData = Keys.None)
\+        public KeyPressEventArgs (char keyChar, string words, Keys keyData = Keys.None)
         {
             KeyChar = keyChar;
             Handled = false;
             key_data = keyData;
\+            Words = words;
         }
         public bool Handled { get; set; }
         public char KeyChar { get; set; }
\+        public string Words { set; get; }
         public bool Alt => key_data.HasFlag (Keys.Alt);
\
\--- a/src/Modern.Forms/TextBox.cs
\+++ b/src/Modern.Forms/TextBox.cs
@@ -212,7 +212,7 @@ namespace Modern.Forms
 \
             // Printable characters (except backspace)
             if (e.KeyChar >= 32 && e.KeyChar != 127) {
\-                if (document.InsertText ((e.KeyChar).ToString ()))
\+                if (document.InsertText (e.Words))
                     ScrollToCaret ();
             }
         }
\--- a/src/Modern.Forms/Window.cs
\+++ b/src/Modern.Forms/Window.cs
@@ -246,7 +246,7 @@ namespace Modern.Forms
                         break;
                 }
             } else if (e is RawTextInputEventArgs te) {
\-                var kp_e = new KeyPressEventArgs (te.Text[0], KeyEventArgs.FromInputModifiers (te.Modifiers));
\+                var kp_e = new KeyPressEventArgs (te.Text[0], te.Text, KeyEventArgs.FromInputModifiers (te.Modifiers));
                 adapter.RaiseKeyPress (kp_e);
                 e.Handled = true;
             }

2. TextBox:when delete words one by one, the last letter always follows and delete the last char get crash.
>\--- a/src/Modern.Forms/TextBoxDocument.cs
\+++ b/src/Modern.Forms/TextBoxDocument.cs
@@ -92,8 +92,7 @@ namespace Modern.Forms
                 var current_caret = block.GetCaretInfo (cursor_index);
                 SetCursorToCharIndex (current_caret.PreviousCodePointIndex);
\
\-                RemoveText (cursor_index - 1, 1);
\+                RemoveText (cursor_index, 1);

3. Suggest Label/TextBox/etc add FontSize, FontColor to custom the single style for the specific control.
Some change like this.

>--- a/src/Modern.Forms/TextBox.cs
\+++ b/src/Modern.Forms/TextBox.cs
@@ -367,6 +367,20 @@ namespace Modern.Forms
             set => document.SelectionEnd = value;
         }
 \
\+        public int FontSize {
\+            set => document.FontSize = value;
\+            get => document.FontSize;
\+        }
\+
\+        public SkiaSharp.SKColor FontColor {
\+            set => document.FontColor = value;
\+        }

Sorry for code format, you have to write manually. Next time I will try to use PR.

**Comment by jpobst** [comment]
Thanks for the fixes!

1) I do not know how to test this.  How do I type a "multi-chars" input?
2) Committed your fix.
3) The way controls styles are currently set up is through the `Style` property.  This can be done on the class level which will style **all** instances of that Control, or the instance level which will only style the individual control.

For example:
```
// Give all TextBoxes red text
TextBox.DefaultStyle.ForegroundColor = SKColors.Red;

// Create a TextBox with blue text
var tb = new TextBox ();
tb.Style.ForegroundColor = SKColors.Blue;
```

I still haven't decided if I like this pattern, but I do like that it gives you a way to change **all** instances, which is something you can't easily do in Winforms.

Having said that, the TextBox was not honoring the styles set here, so I fixed that.  There are likely other Controls that do not correctly honor the styles that will need to be fixed.

**Comment by jzlhll** [comment]
> Thanks for the fixes!
> 
> 1. I do not know how to test this.  How do I type a "multi-chars" input?
> 2. Committed your fix.
> 3. The way control styles are currently set up is through the `Style` property.  This can be done on the class level which will style **all** instances of that Control, or the instance level which will only style the individual control.
> 
> For example:
> 
> ```
> // Give all TextBoxes red text
> TextBox.DefaultStyle.ForegroundColor = SKColors.Red;
> 
> // Create a TextBox with blue text
> var tb = new TextBox ();
> tb.Style.ForegroundColor = SKColors.Blue;
> ```
> 
> I still haven't decided if I like this pattern, but I do like that it gives you a way to change **all** instances, which is something you can't easily do in Winforms.
> 
> Having said that, the TextBox was not honoring the styles set here, so I fixed that. There are likely other Controls that do not correctly honor the styles that will need to be fixed.

OK. 
3. I prefer change for your style. The all instances using a default style I think is a good idea.So 3 should not merge.

1. mutil-chars :
sometimes we input words into textbox, is input with a string, but not one char by one char.
<img width="445" alt="屏幕快照 2020-04-28 下午12 01 35" src="https://user-images.githubusercontent.com/19789292/80445934-09020780-8948-11ea-9143-880c0e4210a6.png">
So the "women" wan't be input together because new KeyPressEventArgs (te.Text[0]) limited.
It will only input the 'w' char.

With this patch, the whole string can input together.

**Comment by jpobst** [comment]
Thanks! I added the multi-char code.  I didn't test it, so hopefully it works!
