### ISSUE TITLE
CPU usage remains high

### ISSUE THREAD

**Issue by marinusmaurice** [modern-forms/Modern.Forms#27]
The following is running the ControlGallery sample app
Go to the buttons tab. Click on some buttons
then go to try and go to the treeview tab. CPU usage remains close to  100%.

![image](https://user-images.githubusercontent.com/75542535/138546486-3654c6bd-2679-44d4-8aee-1b6149794aae.png)

Operating System: Debian GNU/Linux 11
KDE Plasma Version: 5.20.5
KDE Frameworks Version: 5.78.0
Qt Version: 5.15.2
Kernel Version: 5.10.0-9-amd64
OS Type: 64-bit
.Net 5.0.208

**Comment by jpobst** [comment]
Looks like recursing through the directory structure on Linux is a bad idea.  Changed to only do a few levels deep.

Thanks!
