### ISSUE TITLE
Issue with display scaling

### ISSUE THREAD

**Issue by axx0** [modern-forms/Modern.Forms#42]
I have a program which draws a bitmap in the center of a window.

```
using Modern.Forms;
using SkiaSharp;

namespace ModernFormsApp1
{
    public partial class MainForm : Form
    {
        public MainForm()
        {
            Style.BackgroundColor = SKColors.Aquamarine;

            var img = new SKBitmap(200, 200);
            using (SKCanvas c = new SKCanvas(img))
            {
                c.Clear(SKColors.Black);
            }
            
            var pb = new PictureBox
            {
                Left = this.Size.Width / 2 - img.Width / 2,
                Top = this.Size.Height / 2 - img.Height / 2,
                Height = img.Height,
                Width = img.Width,
                Image = img
            };
            Controls.Add(pb);
        }
    }
}
```

On a monitor with a 100% DPI scaling I get this:
![image](https://user-images.githubusercontent.com/21365802/197355649-88ae98f2-4e4c-4262-9898-35493ad60112.png)

However with 125% scaling this is the result:
![image](https://user-images.githubusercontent.com/21365802/197355677-498ed093-6409-49b8-8b2a-66b5031e04aa.png)

So it appears the image isn't scaled (stretched). Is this behavior expected?

**Comment by jpobst** [comment]
I think you want to set `PictureBox.SizeMode = PictureBoxSizeMode.StretchImage`.

**Comment by axx0** [comment]
Works, tnx!
