### ISSUE TITLE
System.Drawing.Common will be only supported on Windows

### ISSUE THREAD

**Issue by dax-leo** [modern-forms/Modern.Forms#50]
Hi,

Do you plan to update WindowKit, considering System.Drawing.Common will drop non-Windows support in >7.0 releases (at least that is what I understood) ?
[https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only](url)
Considering you are already using Skia, replacement should be possible (?).

By the way, not relevant to my comment, I would like to congratulate you for building this cool library. SkiaSharp enables us to have unlimited creativity with custom controls, without any ancient GDI+ Windows nonsense.
I forked your code in attempt to create my own custom controls and add some theme improvements. Looks great!
Integration with other Skia controls (I made example for Microcharts) is simple and straightforward.
![image](https://user-images.githubusercontent.com/70173560/227727205-353b390d-23e9-4a78-8573-418074ae2b24.png)

I am huge fan of dark themes so I made some changes in your Theme manager to support Light and Dark themes.
Considering datagrids are so important I was thinking to migrate ReoGrid (which can serve as gridview and excel clone) to Modern.Forms. 
If/when I do it, I will share the code.

One more time, truly impressive work so far.
![image](https://user-images.githubusercontent.com/70173560/227727289-83d1b656-b263-4a9d-9923-2ec49995c602.png)

**Comment by jpobst** [comment]
Thanks for the kind words!

> Do you plan to update WindowKit, considering System.Drawing.Common will drop non-Windows support in >7.0 releases (at least that is what I understood) ?

I think we are already using it properly, and only using the Windows-specific pieces on Windows.  The parts we use on all platforms are simply structs like `Point` and `Rectangle`.  However if we find a place where we are using one of the listed affected APIs on non-Windows we should definitely look at converting it.

> I am huge fan of dark themes so I made some changes in your Theme manager to support Light and Dark themes.

Looks great!  I strongly dislike dark themes, so I haven't put any work into creating one. 😁 

But there should definitely be one built-in and I would love for someone with more dark theme passion to tackle it.

> Considering datagrids are so important I was thinking to migrate ReoGrid (which can serve as gridview and excel clone) to Modern.Forms

Yeah, a DataGrid is pretty essential to the types of applications Modern.Forms is targeting, but it's also a tremendous amount of work, so it hasn't been tackled yet.  Another option would be to port `DataGridView` from [Microsoft's actual Winforms source](https://github.com/dotnet/winforms/blob/main/src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.cs).  It's probably not as feature-rich, but it's one that would be very familiar for Winforms developers.

I think at this point I don't want to commit to a specific DataGrid implementation, so I had thought it would initially go into a separate library/NuGet until I felt it was mature enough and seemed like the right way to go.

**Comment by dax-leo** [comment]
Hi,

thank you for reply.
UI programming was never my thing considering I work mostly in telecom domain, but now when I have more spare time I really enjoy learning new things.

Here is some good news; I converted my old treeview implementation which is very light grid viewer.
It's now fully SkiaSharp supported.
I am currently adapting treeview filters, editors, scaling etc. (10 years ago scaling was not in my mind :)
![image](https://user-images.githubusercontent.com/70173560/229584568-ab75c43b-0fdf-4a37-b359-06c0a95d2be6.png)

Next to it I also adapted very simple implementation of Html Control. This is stripped down implementation of existing Html Renderer, but I decided not to go with that one due to extreme complexity. I still need to resolve few text measuring bugs, but I am almost there.
![Clipboard01 (1)](https://user-images.githubusercontent.com/70173560/229598173-18de4689-e76d-4e92-b528-88e30cca613d.jpg)

Simple button with context menu as extension to Modern.Forms.Button control. Somehow I use these all the time.
![image](https://user-images.githubusercontent.com/70173560/229587482-f2782b73-af03-4eb6-a49b-430cc932f1c1.png)

Stack Panel (work in progress) - movable tiles with custom controls or html view (for simple dashboard with real time updates- think of weather info etc. ).

Next on my list:
**GMap.NET** - code base looks very organized, I will investigate it.
**ReoGrid** - will drop this one for time being. Unfortunately it's large portion of spaghetti code.
**Windows Charting from .NET** - maybe (?), need to check if Microcharts.Skia is suitable replacement.
**Month Calendar** - need this for my gridview editor considering we can't reuse Win32 wrapper (CPOL license) - https://www.codeproject.com/articles/10840/another-month-calendar

If someone has more ideas just drop link to GitHub project (just please pay attention to license) and let's see what can be done (keep in mind I have normal day job so I will do my best).
I will organize all these projects under Modern.Forms.Extensions GitHub project (coming in few weeks). 
This framework will serve as good replacement for some my Linux C++/QT projects, so for sure I will keep my eye on it for long time.

I can drop any updates here, if you don't mind to keep this discussion open.

Regards,
Darko
