### ISSUE TITLE
Can't use shortcuts!

### ISSUE THREAD

**Issue by W0lfDev** [modern-forms/Modern.Forms#56]
form.KeyUp / KeyDown events are not available

**Comment by dax-leo** [comment]
Hi.

_FYI. I am not the author of this framework, but maybe I can help._

I think is very easy to implement. This is based on Avalonia so the process is similar, just extend WindowBase class (Form inherits from it).

Go to WindowBase.cs and add those 2 events:


        /// <summary>
        /// Raised when key down pressed.
        /// </summary>
        public event EventHandler<KeyEventArgs>? KeyDown;

        /// <summary>
        /// Raised when key up pressed.
        /// </summary>
        public event EventHandler<KeyEventArgs>? KeyUp;


under method OnInput() find the part that handles key down/up press (see my comment lines below).
You can also choose when events will fire. Do you wish to invoke key events on ControlAdapter first, or allow Form to absorb those events before any other control. In my case Control objects will first detect keydown (if used) and then parent Form will follow. Just switch places if you wish to have it other way around.

```
else if (e is RawKeyEventArgs ke) {
                switch (ke.Type) {
                    case RawKeyEventType.KeyDown:
                        var kd_e = new KeyEventArgs (WindowKitExtensions.AddModifiers ((Keys)KeyInterop.VirtualKeyFromKey (ke.Key), ke.Modifiers));
                        adapter.RaiseKeyDown (kd_e);
                        KeyDown?.Invoke (this, kd_e); // <------ add this for keydown (put before adapter if you wish to override)
                        break;
                    case RawKeyEventType.KeyUp:
                        var ku_e = new KeyEventArgs (WindowKitExtensions.AddModifiers ((Keys)KeyInterop.VirtualKeyFromKey (ke.Key), ke.Modifiers));
                        adapter.RaiseKeyUp (ku_e);
                       *KeyUp?.Invoke (this, ku_e); // <------  add this for key up
                        break;
 }
```


In your form now you can attach method call to any of these events:
```
 public MainForm ()
 {            
            KeyDown += (s, e) => { Debug.WriteLine ("Key DOWN pressed"); };
            KeyUp += (s, e) => { Debug.WriteLine ("Key UP pressed"); };
 }
```
