### ISSUE TITLE
App freezes when using open file dialog

### ISSUE THREAD

**Issue by W0lfDev** [modern-forms/Modern.Forms#59]
I was developing an app on linux. After some time I switched to windows and now when i use open file dialog, the whole app freezes.

**Comment by jpobst** [comment]
- Does it just freeze for like 5 seconds? Or does it freeze permanently?
- Does it freeze every time? Or just sometimes?

I have noticed a several second freeze that only happens occasionally.

**Comment by W0lfDev** [comment]
It freezes everytime and i waited for about 2-3 minutes before terminating it. It didnt unfreeze

**Comment by W0lfDev** [comment]
> - Does it just freeze for like 5 seconds? Or does it freeze permanently?
> - Does it freeze every time? Or just sometimes?
> 
> I have noticed a several second freeze that only happens occasionally.

It freezes everytime and i waited for about 2-3 minutes before terminating it. It didnt unfreeze

**Comment by jpobst** [comment]
If you are able to create a simple test case that always freezes that would be helpful.  It happens rarely enough for my test case (`ControlGallery`) that I can't really debug it.

**Comment by W0lfDev** [comment]
> If you are able to create a simple test case that always freezes that would be helpful. It happens rarely enough for my test case (`ControlGallery`) that I can't really debug it.

![Screenshot 2023-07-15 225409](https://github.com/modern-forms/Modern.Forms/assets/96019707/d3b8deea-ba7d-46e0-bc0a-a8712dfd6fe3)

When I call this function it just freezes

Here is a video that shows what happens:
https://github.com/modern-forms/Modern.Forms/assets/96019707/dd7f8b20-5370-4bcc-8fa9-74deba49c5b7

**Comment by jpobst** [comment]
Ah, the old "sync over async" deadlock:
https://devblogs.microsoft.com/pfxteam/await-and-ui-and-deadlocks-oh-my

I'm not sure how to work around this currently.  Likely we probably need to add a sync version for people to easily use.

In the meantime, you will need to use `await` to prevent the deadlock.

Example:

https://github.com/modern-forms/Modern.Forms/blob/main/samples/ControlGallery/Panels/FileDialogPanel.cs#L24-L41

**Comment by W0lfDev** [comment]
> 

This works, but how can i tell it to wait until I hit OK in file explorer. Currently it doesn't wait.


https://github.com/modern-forms/Modern.Forms/assets/96019707/3ede2578-2793-4e59-ad9b-5c579bdcdf23

**Comment by jpobst** [comment]
I'm not sure what you mean by "it doesn't wait".

The error you are hitting looks like https://github.com/modern-forms/Modern.Forms/issues/40.

I am guessing you are using a NuGet package rather than building `Modern.Forms` from source?

You will likely want to build from source to ensure you have the latest fixes.

**Comment by W0lfDev** [comment]
> I'm not sure what you mean by "it doesn't wait".
> 
> The error you are hitting looks like #40.
> 
> I am guessing you are using a NuGet package rather than building `Modern.Forms` from source?
> 
> You will likely want to build from source to ensure you have the latest fixes.

The behavior of the open file dialog should be this:
Open Existing -> *wait until i select file and click OK* -> *open editor (the other window) -> *load data* -> etc...

Currently when i hit Open Existing it opens the file dialog but also opens the editor

**Comment by W0lfDev** [comment]
Ok. so i was a problem on my end. I didn't put the open file dialog where it needed to be. 
In my case i had to call OpenFileDialog before I opened my other form.

Hope this helps :D
