### ISSUE TITLE
Popup Windows not closing on Form click/move.

### ISSUE THREAD

**Issue by dax-leo** [modern-forms/Modern.Forms#65]
Problem description:
1. open combobox
![image](https://github.com/modern-forms/Modern.Forms/assets/70173560/ec00120e-37b8-439c-a782-dde36dcfde66)
2. We can move the form but combobox will stay open.
![image](https://github.com/modern-forms/Modern.Forms/assets/70173560/f5714c46-17d8-4f89-9e9e-8854b37eaced)

Maybe changing :
https://github.com/modern-forms/Modern.Forms/blob/20a1f069d6657371505876d282247bdd09f66931/src/Modern.Forms/FormTitleBar.cs#L105-L112

to :
```
protected override void OnMouseDown (MouseEventArgs e)
        {
            base.OnMouseDown (e);

            // Reset any popup left open
            FindForm ().adapter.SelectedControl?.Deselect ();
            FindForm ().adapter.SelectedControl?.Select ();

            // We won't get a MouseUp from the system for this, so don't capture the mouse
            Capture = false;
            FindForm ()?.BeginMoveDrag ();
        }
```

This way parent control (that is FindForm ().adapter.SelectedControl) will automatically trigger popup close.

**Comment by jpobst** [comment]
Should be fixed with #66.  I tried to unify the code a bit with the existing mechanism that handles this for menus.
