### ISSUE TITLE
ActivePopupWindow reference update

### ISSUE THREAD

**Issue by dax-leo** [modern-forms/Modern.Forms#71]
Hi,

just a small improvement idea.

The line of code below should be within PopupWindow Show(), not within Control implementing PopupWindow.
https://github.com/modern-forms/Modern.Forms/blob/504a7bf6c7747a2ec7709c657b226a59e75b8187/src/Modern.Forms/ComboBox.cs#L83

(PopupWindow) What we have now:
https://github.com/modern-forms/Modern.Forms/blob/504a7bf6c7747a2ec7709c657b226a59e75b8187/src/Modern.Forms/PopupWindow.cs#L41-L56

(PopupWindow) We should change into:
![image](https://github.com/modern-forms/Modern.Forms/assets/70173560/ef835fcb-c76a-4fe2-80c7-0d285ca141a3)

Reason:
Not possible to (properly) use PopupWindow as a standalone control (**ApplicApplication.ActivePopupWindow** is internal).
PopupWindow should be responsible to change ActivePopupWindow reference, not the control implementing it.

**Comment by jpobst** [comment]
Good suggestion, that makes a lot more sense!
