### ISSUE TITLE
Application.ClosePopups issue.

### ISSUE THREAD

**Issue by dax-leo** [modern-forms/Modern.Forms#72]
Can you please investigate this one. 
I compiled the latest changes but it looks like recent change related to Application.ClosePopups() might be causing some problems.

Control.RaiseMouseDown() will always trigger close of any popup if you click on a control within Popup window (try it with ComboBox, if you click on scrollbar notice popup automatically disappears).

Try to drag scrollbar... 
![image](https://github.com/modern-forms/Modern.Forms/assets/70173560/1ef9b254-4938-464f-8f8e-0e5da153ba2a)
gone....  :(
![image](https://github.com/modern-forms/Modern.Forms/assets/70173560/dbba5f42-58c5-4e18-a34f-962c0cbfa58a)

How about having Close placed into separate methods (CloseMenus() and ClosePopups()) ?
And then modify RaiseMouseDown (?)

https://github.com/modern-forms/Modern.Forms/blob/504a7bf6c7747a2ec7709c657b226a59e75b8187/src/Modern.Forms/Control.cs#L1401
This worked for me :
```
 internal void RaiseMouseDown(MouseEventArgs e) 
{

            var child = Controls.GetAllControls().LastOrDefault(c => c.Visible && c.GetControlBehavior(ControlBehaviors.ReceivesMouseEvents) && c.ScaledBounds.Contains(e.Location));

            if (child != null)
                child.RaiseMouseDown(TranslateMouseEvents(e, child));
            else
            {
                // If we're clicking on the a Control that isn't the active menu, 
                // we need to close the active menu (if any)

                if ((this as MenuBase)?.GetTopLevelMenu() != Application.ActiveMenu || Application.ActiveMenu is null)
                    Application.CloseMenus();

                // If we're clicking on the a Control that isn't child of PopupWindow, 
                // we need to close the active popup (if any)

                if (Application.ActivePopupWindow != null && this.FindWindow() is not PopupWindow)
                    Application.ClosePopups();

                if (Enabled)
                {
                    Select();
                    Capture = true;
                    OnMouseDown(e);
                }
            }
        }
```

Please see if my suggestion makes sense.

**Comment by jpobst** [comment]
Fix looks good to me.  Thanks!
