### ISSUE TITLE
Is this project still being developed?

### ISSUE THREAD

**Issue by iahung3** [modern-forms/Modern.Forms#75]
This is a serious question, as .NET Core has gained native WinForms support now. Is there any reason for the continuation of this project?

**Comment by TheColonel2688** [comment]
Last I checked .NetCore winforms was windows only.

**Comment by jpobst** [comment]
Correct, Winforms is Windows only.  One of the goals of this project is to provide a similar experience that works on Mac and Linux.

**Comment by iahung3** [comment]
Yes, I understand. But, no new commits for several months. Is this project still being developed?

**Comment by jpobst** [comment]
If you are looking for a mature supported project, you probably want to look elsewhere.

This is my side project, sometimes I feel like working on it, and sometimes I don't.  😁
