### ISSUE TITLE
How to disable the terminal when run on OSX?

### ISSUE THREAD

**Issue by jzlhll** [modern-forms/Modern.Forms#8]
When run on OSX, first it will show a terminal. How I can disable it and directly show the GUI?

**Comment by maximilien-noal** [comment]
I use :

<TargetFramework>netcoreapp3.0</TargetFramework>
<OutputType>WinExe</OutputType>

To get rid of it with AvaloniaUI. Perhaps it will work also here ?

**Comment by jzlhll** [comment]
> I use :
> 
> ```
> 
> <TargetFramework>netcoreapp3.0</TargetFramework>
> <OutputType>WinExe</OutputType>
> ```
> 
> To get rid of it with AvaloniaUI. Perhaps it will work also here ?

It used already, still open the gui from terminal.

**Comment by jzlhll** [comment]
I found a way. NuGet "NSubsys" and manual 'dotnet publish'
