### ISSUE TITLE
TextBox DeleteHighlightedText crash

### ISSUE THREAD

**Issue by jzlhll** [modern-forms/Modern.Forms#9]
![TIM截图20191201230925](https://user-images.githubusercontent.com/19789292/69916071-3fb71d00-1491-11ea-9e94-88d421e87fd6.png)

It is easy to reproduce this issue,please check it.

**Comment by jpobst** [comment]
I can't figure out the steps to make this crash occur, can you please add them?

**Comment by jzlhll** [comment]
1. On OSX, when input words, it will input the terminal, but not in this textbox;
2. On windows10, when using mouse to select words, and as the same time to input words, it will crash.

**Comment by jzlhll** [comment]
windows is ok.
While on OSX the textbox input is still out to terminal, and get crash.

11112233444222019-12-04 10:44:10.896 dotnet[3681:2549534] WARNING: NSWindow drag regions should only be invalidated on the Main Thread! This will throw an exception in the future. Called from (
	0   AppKit                              0x00007fff2a158607 -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 378
	1   AppKit                              0x00007fff2a1559f7 -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 1479
	2   AppKit                              0x00007fff2a15542a -[NSWindow initWithContentRect:styleMask:backing:defer:] + 45
	3   AppKit                              0x00007fff2a9b6753 -[NSWindow init] + 75
	4   libAvaloniaNative.dylib             0x000000010e8f73cf -[AvnWindow initWithParent:] + 63
	5   libAvaloniaNative.dylib             0x000000010e8f8efd _ZN14WindowBaseImplC2EP20IAvnWindowBaseEvents + 445
	6   libAvaloniaNative.dylib             0x000000010e8f8b06 _ZN10WindowImplC1EP16IAvnWindowEvents + 134
	7   libAvaloniaNative.dylib             0x000000010e8f8a0b _Z15CreateAvnWindowP16IAvnWindowEvents + 59
	8   libAvaloniaNative.dylib             0x000000010e8ef22f _ZN14AvaloniaNative12CreateWindowEP16IAvnWindowEventsPP10IAvnWindow + 63
	9   ???                                 0x0000000113c2d4c2 0x0 + 4626502850
	10  ???                                 0x0000000113c2d012 0x0 + 4626501650
	11  ???                                 0x0000000113c2cf19 0x0 + 4626501401
	12  ???                                 0x0000000113c1225f 0x0 + 4626391647
	13  ???                                 0x00000001145c1a79 0x0 + 4636547705
	14  ???                                 0x00000001145c19e3 0x0 + 4636547555
	15  ???                                 0x00000001145c197f 0x0 + 4636547455
	16  ???                                 0x00000001145c16ff 0x0 + 4636546815
	17  ???                                 0x00000001137447f1 0x0 + 4621354993
	18  ???                                 0x000000011374a1e2 0x0 + 4621378018
	19  ???                                 0x000000011372ed82 0x0 + 4621266306
	20  ???                                 0x0000000113744661 0x0 + 4621354593
	21  ???                                 0x0000000113744478 0x0 + 4621354104
	22  ???                                 0x000000011374440b 0x0 + 4621353995
	23  ???                                 0x0000000113726beb 0x0 + 4621233131
	24  libcoreclr.dylib                    0x000000010cfe4029 _ZN18MethodDescCallSite16CallTargetWorkerEPKmPmi + 1657
	25  libcoreclr.dylib                    0x000000010cffeef8 _Z32QueueUserWorkItemManagedCallbackPv + 184
	26  libcoreclr.dylib                    0x000000010cfa4fa3 _ZL31ManagedThreadBase_DispatchOuterP22ManagedThreadCallState + 323
	27  libcoreclr.dylib                    0x000000010cfa55c0 _ZN17ManagedThreadBase10ThreadPoolEPFvPvES0_ + 32
	28  libcoreclr.dylib                    0x000000010cf9bcb4 _ZN26ManagedPerAppDomainTPCount16DispatchWorkItemEPbS0_ + 276
	29  libcoreclr.dylib                    0x000000010cfc95cf _ZN13ThreadpoolMgr17WorkerThreadStartEPv + 1311
	30  libcoreclr.dylib                    0x000000010ce1d384 _ZN7CorUnix10CPalThread11ThreadEntryEPv + 436
	31  libsystem_pthread.dylib             0x00007fff58c4c2eb _pthread_body + 126
	32  libsystem_pthread.dylib             0x00007fff58c4f249 _pthread_start + 66
	33  libsystem_pthread.dylib             0x00007fff58c4b40d thread_start + 13

**Comment by jpobst** [comment]
I haven't been able to figure out the issue with keystrokes not getting captured on OSX, and I can't get Avalonia to run without crashing right now on OSX so I can't compare.  I'll have to retry some time later.

**Comment by jpobst** [comment]
Looks like it's related to not using OSX window decorations.  Commenting out this line seems to fix it:

https://github.com/modern-forms/Modern.Forms/blob/master/src/Modern.Forms/Form.cs#L28

**Comment by jzlhll** [comment]
It is about the action when input . When input words, on osx it will input to the terminal but not in the textbox.

**Comment by jpobst** [comment]
Did you try commenting out that line? That fixes it for me, but obviously it makes the window look weird.

**Comment by jzlhll** [comment]
I already try it.But still like that, and the window look weird.

**Comment by jpobst** [comment]
Looks like I mixed up what actually fixed it for me.  It was actually this commit updating the Avalonia Mac backend: https://github.com/modern-forms/Modern.Forms/commit/0006e5aeacb27136e2b9021984b48e5f7124e609.

So updating to the latest should fix it.

**Comment by jpobst** [comment]
Closing because I think this is fixed. If it still occurs, please feel free to reopen.
